<a href="https://colab.research.google.com/github/Manasi200/Track-release-prediction/blob/main/MS_Release_year_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00203/YearPredictionMSD.txt.zip &> /dev/null

In [ ]:
# Creating a folder for the unzipped file
!mkdir /content/drive/MyDrive/deep-learning/proj2_assets

# Unzipping the compressed file to the new folder
!unzip /content/YearPredictionMSD.txt.zip -d /content/drive/MyDrive/deep-learning/proj2_assets

# Renaming the unzipped file songdata.txt
!mv /content/drive/MyDrive/deep-learning/proj2_assets/YearPredictionMSD.txt /content/drive/MyDrive/deep-learning/proj2_assets/songdata.txt

mkdir: cannot create directory ‘/content/drive/MyDrive/deep-learning/proj2_assets’: File exists
Archive:  /content/YearPredictionMSD.txt.zip
  inflating: /content/drive/MyDrive/deep-learning/proj2_assets/YearPredictionMSD.txt

In [ ]:
# Importing the pandas library
import pandas as pd

# Configuring display settings of pandas output
pd.set_option('precision', 3)
pd.set_option('display.width', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.float_format', '{:.3f}'.format)

In [ ]:
BASE_PATH = '/content/drive/MyDrive/deep-learning/proj2_assets/'

In [ ]:
df = pd.read_csv(BASE_PATH + 'songdata.txt', header=None)

In [ ]:
df.head(1)

     0      1      2      3     4       5       6       7       8     9      10    11     12     13      14      15      16      17      18      19      20      21      22      23      24     25       26     27     28      29      30    31     32     33    34    35     36       37      38      39     40      41     42      43      44     45      46     47      48      49     50      51     52     53     54     55      56      57     58     59      60     61    62      63      64      65      66    67     68     69    70      71      72     73    74     75     76      77     78      79     80     81      82     83     84    85      86     87     88      89    90
0  2001 49.944 21.471 73.078 8.749 -17.406 -13.099 -25.012 -12.233 7.831 -2.468 3.321 -2.315 10.206 611.109 951.090 698.114 408.985 383.709 326.515 238.113 251.424 187.174 100.427 179.195 -8.416 -317.870 95.863 48.103 -95.663 -18.062 1.970 34.424 11.727 1.368 7.794 -0.370 -133.679 -83.262 -37.298 73.047 -37.367 -3.139 -24.215 -13.231 15.938 -18.605 82.155 240.580 -10.294 31.584 -25.382 -3.908 13.293 41.551 -7.263 -21.009 105.508 64.299 26.085 -44.591 -8.307 7.937 -10.737 -95.448 -82.033 -35.592 4.695 70.956 28.091 6.020 -37.138 -41.124 -8.408 7.199 -8.602 -5.909 -12.324 14.687 -54.321 40.148 13.016 -54.405 58.994 15.373 1.111 -23.088 68.408 -1.822 -27.463 2.263

In [ ]:
df.columns.dtype

dtype('int64')

In [ ]:
# Converting the column names to strings
df.columns = df.columns.astype(str)

In [ ]:
# Assigning the name target to column 0
df.rename(columns={'0': 'target'}, inplace=True)

In [ ]:
# Prefixing col_ to the other column names
features = df.columns[~df.columns.isin(['target'])]
df.rename(columns = dict(zip(features, 'col_' + features)), inplace=True)

In [ ]:
df.head()

   target  col_1  col_2  col_3  col_4   col_5   col_6   col_7   col_8  col_9  col_10  col_11  col_12  col_13   col_14   col_15  col_16  col_17  col_18  col_19  col_20  col_21  col_22  col_23  col_24  col_25   col_26   col_27  col_28   col_29  col_30  col_31  col_32  col_33  col_34  col_35  col_36   col_37   col_38   col_39  col_40  col_41  col_42  col_43  col_44  col_45  col_46   col_47  col_48  col_49  col_50  col_51  col_52  col_53  col_54  col_55   col_56  col_57   col_58  col_59  col_60  col_61  col_62  col_63   col_64   col_65  col_66  col_67  col_68  col_69  col_70   col_71  col_72  col_73  col_74  col_75  col_76  col_77  col_78  col_79  col_80  col_81   col_82  col_83  col_84  col_85  col_86   col_87  col_88  col_89  col_90
0    2001 49.944 21.471 73.078  8.749 -17.406 -13.099 -25.012 -12.233  7.831  -2.468   3.321  -2.315  10.206  611.109  951.090 698.114 408.985 383.709 326.515 238.113 251.424 187.174 100.427 179.195  -8.416 -317.870   95.863  48.103  -95.663 -18.062   1.970  34.424  11.727   1.368   7.794  -0.370 -133.679  -83.262  -37.298  73.047 -37.367  -3.139 -24.215 -13.231  15.938 -18.605   82.155 240.580 -10.294  31.584 -25.382  -3.908  13.293  41.551  -7.263  -21.009 105.508   64.299  26.085 -44.591  -8.307   7.937 -10.737  -95.448  -82.033 -35.592   4.695  70.956  28.091   6.020  -37.138 -41.124  -8.408   7.199  -8.602  -5.909 -12.324  14.687 -54.321  40.148  13.016  -54.405  58.994  15.373   1.111 -23.088   68.408  -1.822 -27.463   2.263
1    2001 48.732 18.429 70.327 12.946 -10.324 -24.838   8.766  -0.920 18.765   4.592   2.219   0.340  44.390 2056.938  605.407 457.412 777.153 415.649 746.478 366.453 317.829 273.079 141.759 317.353  19.483  -65.255  162.751 135.008  -96.284 -86.880  17.381  45.907  32.499 -32.854  45.108  26.849 -302.573  -41.719 -138.850 202.187 -33.443 195.047 -16.932  -1.092 -25.381 -12.190 -125.948 121.742 136.671  41.182  28.551   1.523  70.995 -43.631 -42.550  129.828  79.954  -87.146 -45.754 -65.821 -43.900 -19.457  12.592 -407.641   42.912  12.159 -88.379  42.252  46.492 -30.177   45.985 130.479  13.883  -4.001  17.860 -18.321 -87.991  14.375 -22.701 -58.813   5.668  -19.681  33.050  42.878  -9.904 -32.228   70.494  12.049  58.435  26.921
2    2001 50.957 31.856 55.819 13.417  -6.579 -18.549  -3.279  -2.350 16.070   1.395   2.736   0.828   7.466  699.545 1016.010 594.067 355.737 507.399 387.699 287.153 112.372 161.689 144.144 199.297  -4.244 -297.006 -148.364  -7.947  -18.716  12.775 -25.377   9.714   0.138  26.797   6.308  28.701  -74.890 -289.196 -166.261  13.093   5.891   6.890 -10.972   1.676  11.435  -7.280  133.082 141.868 -56.994  98.160  18.509  16.972  24.266 -10.508  -8.684   54.758 194.740    7.960 -18.227   0.065  -2.631  26.026   1.757 -262.369 -233.601  -2.505 -12.143  81.376   2.076  -1.824  183.653  22.648 -39.989  43.374 -31.567  -4.888 -36.532 -23.947 -84.193  66.005   3.038   26.059 -50.928  10.938  -0.076  43.201 -115.007  -0.059  39.671  -0.663
3    2001 48.248 -1.898 36.298  2.588   0.972 -26.217   5.051 -10.341  3.550  -6.363   6.630  -3.351  37.641 2174.082  697.433 459.246 742.790 229.308 387.897 249.067 245.899 176.205  98.822 150.973  78.491  -62.003   43.497 -96.427 -108.966  14.229  14.542 -23.556 -39.370 -43.592  20.837  35.639 -181.349  -93.666  -90.556  -0.017  23.227 -25.483 -25.881  12.592 -24.851  -7.207  778.022  61.159  23.376 -97.649   4.569 -37.323   4.152  12.243  35.027 -178.896  82.466  -20.494 101.786 -19.778 -21.527   3.363 -11.632   51.554  -50.576 -28.148 -83.158  -7.353 -22.115   1.183 -122.705 150.574  24.375  41.198 -37.043 -28.730 162.196  22.183  -8.635  85.234  34.573 -171.707 -16.967 -46.676 -12.515  82.581  -72.090   9.906 199.630  18.854
4    2001 50.970 42.210 67.100  8.468 -15.853 -16.814 -12.482  -9.376 12.637   0.936   1.609   2.192  47.321  894.285  809.866 318.786 435.045 341.615 334.307 322.996 190.619 235.847  96.895 210.589   5.605 -199.640  204.858 -77.177  -65.797  -6.951 -12.153  -3.854  20.690 -20.305  37.150  11.207 -124.095 -295.985  -33.312  28.688 -32.740 -26.610 -69.075   5.735 -15.480 -15.553  150.297 176.960  58.180  25.970  45.255  10.422  27.888 -17.127 -31.548  -76.863  41.173 -138.325 -53.969 -21.303 -24.874  -2.466  -4.050  -56.512  -34.564  -5.071 -47.756  64.815 -97.429 -12.594   55.237  28.857  54.535 -31.971  20.033  -8.079 -55.126  26.590 -10.272 -30.642   9.927  -55.957  64.927 -17.725  -1.492  -7.500   51.766   7.887  55.669  28.749

In [ ]:
# Printing the number of rows and columns of df and
# determining the number of null values
df.shape, df.isnull().sum().sum()

((515345, 91), 0)

In [ ]:
# Obtaining a statistical description of the data in df
df.describe()

,target,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25,col_26,col_27,col_28,col_29,col_30,col_31,col_32,col_33,col_34,col_35,col_36,col_37,col_38,col_39,col_40,col_41,col_42,col_43,col_44,col_45,col_46,col_47,col_48,col_49,col_50,col_51,col_52,col_53,col_54,col_55,col_56,col_57,col_58,col_59,col_60,col_61,col_62,col_63,col_64,col_65,col_66,col_67,col_68,col_69,col_70,col_71,col_72,col_73,col_74,col_75,col_76,col_77,col_78,col_79,col_80,col_81,col_82,col_83,col_84,col_85,col_86,col_87,col_88,col_89,col_90
count,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000,515345.000
mean,1998.397,43.387,1.290,8.658,1.164,-6.554,-9.522,-2.391,-1.793,3.728,1.882,-0.147,2.546,33.714,2439.359,1967.734,1514.860,910.981,879.147,603.737,517.579,393.962,325.733,288.885,291.973,43.032,43.315,-46.449,-27.673,14.958,44.515,5.132,24.034,9.499,-4.179,0.499,72.652,-51.441,117.921,-189.881,23.096,-1.283,18.148,-51.959,3.233,-1.488,6.334,78.702,142.697,-86.516,25.241,6.379,28.294,12.772,1.700,-10.205,64.101,104.822,-0.026,38.678,-27.990,3.302,0.307,-0.479,-138.223,-0.696,0.243,3.152,27.643,31.822,-0.836,-8.932,4.849,-27.348,-11.939,-21.572,-5.576,-23.304,31.113,-104.975,26.962,15.755,-73.461,41.542,37.934,0.316,17.669,-26.315,4.459,20.035,1.329
std,10.931,6.068,51.580,35.269,16.323,22.861,12.858,14.572,7.964,10.583,6.530,4.371,8.320,22.260,1749.368,1261.485,1092.831,475.708,576.866,317.499,309.365,214.014,165.699,186.961,153.476,121.429,715.759,544.880,218.368,163.216,134.888,99.088,71.810,74.412,53.517,42.490,107.913,415.039,453.399,260.645,205.740,119.833,119.846,73.622,38.374,41.545,54.974,470.597,262.370,209.533,122.154,93.556,75.049,69.982,83.279,57.807,273.827,311.135,266.774,169.072,144.083,59.447,49.181,37.675,308.187,222.199,128.141,99.921,116.696,106.360,36.799,251.607,229.060,163.783,63.289,64.692,26.358,268.191,144.156,201.138,123.848,32.100,175.619,122.229,95.051,16.162,114.428,173.977,13.347,185.558,22.089
min,1922.000,1.749,-337.092,-301.005,-154.184,-181.953,-81.794,-188.214,-72.504,-126.479,-41.632,-69.681,-94.042,0.133,8.474,21.214,17.858,12.150,5.518,19.809,6.255,6.184,15.307,6.116,5.177,-2821.430,-13390.361,-12017.089,-4324.865,-3357.280,-3115.375,-3805.666,-1516.356,-1679.118,-1590.637,-989.646,-1711.484,-8448.195,-10095.726,-9803.759,-7882.823,-4673.355,-4175.413,-4975.382,-1072.956,-1021.289,-1329.960,-14861.695,-3992.689,-6642.400,-2344.526,-2270.811,-1746.478,-3188.177,-2199.782,-1694.260,-5154.024,-5111.602,-4730.599,-3756.491,-2499.955,-1900.105,-1396.702,-600.091,-10345.833,-7375.977,-3896.275,-1199.004,-2564.788,-1904.984,-974.702,-7057.712,-6953.357,-8400.603,-1812.889,-1387.505,-718.421,-9831.454,-2025.778,-8390.035,-4754.937,-437.722,-4402.376,-1810.689,-3098.350,-341.789,-3168.925,-4319.992,-236.039,-7458.378,-381.424
25%,1994.000,39.955,-26.060,-11.463,-8.488,-20.666,-18.441,-10.781,-6.468,-2.294,-2.445,-2.652,-2.550,18.242,1315.621,1113.536,814.970,606.539,487.855,392.373,318.616,257.542,214.016,167.706,197.512,-11.648,-288.586,-250.757,-118.556,-60.178,-24.440,-38.592,-6.465,-24.776,-28.677,-16.990,14.480,-223.792,-99.582,-289.716,-69.673,-53.525,-27.221,-79.160,-14.581,-20.727,-17.317,-113.669,10.525,-157.587,-24.539,-38.698,-9.109,-18.087,-33.963,-28.915,-68.546,-38.783,-117.336,-44.393,-94.413,-25.214,-21.627,-18.718,-262.968,-87.196,-52.088,-46.436,-19.444,-19.613,-16.138,-96.261,-90.680,-86.435,-42.890,-50.807,-15.041,-149.564,-31.727,-163.448,-27.933,-1.813,-139.555,-20.987,-4.670,-6.782,-31.581,-101.530,-2.566,-59.509,-8.820
50%,2002.000,44.258,8.418,10.476,-0.653,-6.008,-11.188,-2.047,-1.736,3.822,1.784,-0.098,2.314,29.095,2009.306,1687.787,1240.770,817.273,739.486,541.535,444.777,349.743,292.736,242.081,264.093,27.642,-43.241,-38.940,-23.427,7.756,30.074,4.116,23.121,7.833,-9.721,3.205,56.222,-73.224,79.929,-160.491,21.140,-4.218,25.805,-45.391,3.370,-0.917,3.956,75.074,105.595,-62.764,31.515,5.133,25.752,9.002,0.590,-1.947,29.874,85.724,-16.143,27.750,-31.408,-0.295,1.688,-3.299,-115.997,8.449,4.821,2.255,18.041,22.273,-0.767,14.768,12.271,-19.809,-12.369,-16.760,-2.449,-56.270,38.801,-71.408,26.897,9.172,-53.090,28.791,33.624,0.821,15.598,-21.204,3.118,7.760,0.053
75%,2006.000,47.834,36.124,29.765,8.788,7.742,-2.389,6.509,2.913,9.962,6.147,2.436,7.360,43.426,3041.982,2489.338,1892.120,1100.852,1114.243,740.737,626.968,476.075,397.491,356.184,349.472,88.765,284.109,167.475,65.827,84.479,97.439,48.707,55.623,40.983,12.297,20.802,116.844,85.715,307.204,-60.266,115.104,46.812,75.732,-17.991,21.656,19.249,28.015,282.455,241.191,12.182,85.620,50.570,62.441,39.466,37.242,18.599,163.684,225.344,86.783,111.072,30.691,27.235,23.673,14.848,1.160,105.677,54.158,51.591,61.130,72.493,14.771,109.779,103.556,42.525,17.314,11.494,7.564,62.153,105.502,-7.332,85.645,26.274,13.479,89.662,77.786,8.471,67.795,52.389,9.968,86.352,9.680
max,2011.000,61.970,384.066,322.851,335.772,262.069,166.237,172.403,126.741,146.298,60.345,88.021,87.913,549.765,65735.780,36816.790,31849.487,19865.932,16831.949,11901.705,9569.778,9616.616,3721.873,6737.122,9813.234,2049.604,24479.665,14505.342,3410.616,3277.634,3553.185,2347.415,1954.355,2887.846,2330.334,1813.237,2496.123,14148.998,8059.146,6065.055,8360.146,3537.504,3892.125,1202.492,1830.545,746.707,1198.627,9059.760,6967.640,6172.345,2067.204,1426.848,2460.433,2394.662,2900.520,569.136,6955.415,12700.014,13001.259,5419.277,5690.292,1811.229,973.053,812.424,11048.198,2877.739,3447.479,2055.039,4779.800,5286.822,745.503,3958.070,4741.181,2124.101,1639.930,1278.333,741.029,10020.283,3423.595,5188.327,3735.026,840.973,4469.455,3210.702,1734.080,260.545,3662.066,2833.609,463.420,7393.398,677.900

In [ ]:
# Listing the unique data types in df and
# the number of columns of each data type
df.dtypes.value_counts()

float64    90
int64       1
dtype: int64

In [ ]:
df.to_feather(BASE_PATH + 'df_original')

In [ ]:
# Importing the saved dataframe
df = pd.read_feather(BASE_PATH + 'df_original')

# Verifying that the dataframe contains the right
# data: strings as column names and valid values
print('-'*31)
print(f'Data type of df columns: {df.columns.dtype}')
print('-'*31)

df.head(1)

-------------------------------
Data type of df columns: object
-------------------------------

   target  col_1  col_2  col_3  col_4   col_5   col_6   col_7   col_8  col_9  col_10  col_11  col_12  col_13  col_14  col_15  col_16  col_17  col_18  col_19  col_20  col_21  col_22  col_23  col_24  col_25   col_26  col_27  col_28  col_29  col_30  col_31  col_32  col_33  col_34  col_35  col_36   col_37  col_38  col_39  col_40  col_41  col_42  col_43  col_44  col_45  col_46  col_47  col_48  col_49  col_50  col_51  col_52  col_53  col_54  col_55  col_56  col_57  col_58  col_59  col_60  col_61  col_62  col_63  col_64  col_65  col_66  col_67  col_68  col_69  col_70  col_71  col_72  col_73  col_74  col_75  col_76  col_77  col_78  col_79  col_80  col_81  col_82  col_83  col_84  col_85  col_86  col_87  col_88  col_89  col_90
0    2001 49.944 21.471 73.078  8.749 -17.406 -13.099 -25.012 -12.233  7.831  -2.468   3.321  -2.315  10.206 611.109 951.090 698.114 408.985 383.709 326.515 238.113 251.424 187.174 100.427 179.195  -8.416 -317.870  95.863  48.103 -95.663 -18.062   1.970  34.424  11.727   1.368   7.794  -0.370 -133.679 -83.262 -37.298  73.047 -37.367  -3.139 -24.215 -13.231  15.938 -18.605  82.155 240.580 -10.294  31.584 -25.382  -3.908  13.293  41.551  -7.263 -21.009 105.508  64.299  26.085 -44.591  -8.307   7.937 -10.737 -95.448 -82.033 -35.592   4.695  70.956  28.091   6.020 -37.138 -41.124  -8.408   7.199  -8.602  -5.909 -12.324  14.687 -54.321  40.148  13.016 -54.405  58.994  15.373   1.111 -23.088  68.408  -1.822 -27.463   2.263

In [ ]:
seed = 123
df = df.sample(frac=1, random_state=seed)

X = df.iloc[:, 1:]

Y = df.iloc[:, 0]

In [ ]:
# Standardizing X
X = (X - X.mean())/X.std()

# Printing the first five rows of standardized X
X.head()

        col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  col_10  col_11  col_12  col_13  col_14  col_15  col_16  col_17  col_18  col_19  col_20  col_21  col_22  col_23  col_24  col_25  col_26  col_27  col_28  col_29  col_30  col_31  col_32  col_33  col_34  col_35  col_36  col_37  col_38  col_39  col_40  col_41  col_42  col_43  col_44  col_45  col_46  col_47  col_48  col_49  col_50  col_51  col_52  col_53  col_54  col_55  col_56  col_57  col_58  col_59  col_60  col_61  col_62  col_63  col_64  col_65  col_66  col_67  col_68  col_69  col_70  col_71  col_72  col_73  col_74  col_75  col_76  col_77  col_78  col_79  col_80  col_81  col_82  col_83  col_84  col_85  col_86  col_87  col_88  col_89  col_90
311436  0.953  1.191  0.160 -1.109 -0.330 -0.557 -1.180 -0.711  0.625  -0.092  -0.474  -1.016   0.001  -0.954  -0.952  -0.785  -0.547  -0.896  -0.510  -0.909  -0.724  -1.007  -0.896  -0.574  -0.218  -0.361   0.227  -0.055  -0.259  -0.633   0.905  -0.694   0.054  -0.419   0.034  -0.923  -0.209  -0.472   0.431   0.828  -0.291  -0.760   0.363   0.721  -0.221  -0.589   0.102  -0.081  -0.452   0.883   0.120  -0.104  -0.636  -0.138   0.335   0.035  -0.605  -0.283  -0.484  -0.146  -1.078   0.185  -0.715   0.999  -0.158   0.363   0.682   0.116  -0.109   0.774   0.497   0.529   0.061  -0.831   0.647   0.643  -0.772   0.058   0.529   0.043  -0.810   0.075  -0.008   0.191   0.021  -0.498  -0.113  -0.560   0.083  -0.065
157334 -0.552  0.728 -0.127 -0.308  1.158  1.093 -1.226 -0.217 -1.259   0.066  -1.429   0.525   0.885   0.375   1.368   0.850   1.629   0.148  -0.071   1.727   1.705   1.822   0.663  -0.045   0.083  -0.344   0.535   0.105  -0.769   0.504  -1.064   1.081   0.213  -0.216  -0.797  -0.809  -0.258   1.292  -1.007   1.671  -0.771  -0.226  -1.072  -0.792   0.266   0.208  -1.073  -0.490  -0.814   0.050  -1.028   0.741   2.585  -0.480   0.271   0.551   0.861   0.195   2.912   0.095  -0.241  -0.596   1.442   0.064   1.040   0.111   2.173  -0.914   0.576  -0.558  -1.238   0.095  -0.675  -1.291  -0.144   0.512  -0.528  -0.104  -0.630  -0.094   0.900  -1.648   0.540   0.251   1.649  -0.029  -0.097  -1.079  -0.113  -0.431
175479 -0.822 -1.918  2.096  1.313 -1.229  4.121 -3.119  0.078  1.657   0.414  -0.587   2.127  -0.070   0.049   1.336   2.416   0.317   1.075   0.482   0.276   1.034   0.849   2.912   0.877   0.487   1.232  -1.138  -0.656  -0.483   1.000   0.249   0.187  -0.435   2.534  -1.511   1.506   0.948   1.154  -2.550   0.917   0.386   0.462   0.006   0.432  -1.184   1.508  -0.565  -0.255  -2.207   0.372  -0.702   1.289  -1.808   2.411  -0.124   0.971   1.762   0.740   1.107   1.140   2.663  -0.143   0.210  -0.322  -0.592   1.436   1.035  -0.951   1.308   0.545  -0.749   2.756  -2.420   0.049  -1.237  -0.531   0.970  -1.556  -3.825   0.388   1.844  -1.329   2.267   2.526  -2.588  -0.901   2.477  -0.528   0.979   2.238
104208 -0.045 -0.842  0.263 -0.862 -0.283  0.049 -0.730 -1.093 -0.089  -1.172  -0.092  -0.848  -0.499  -0.045   0.094  -0.165   0.421  -0.740  -0.187  -0.079   0.273   0.023  -0.516   0.383  -0.337   0.223   0.119   0.153  -0.706   0.157  -0.737  -0.276   0.696  -0.247  -0.356  -0.038  -0.413   0.354  -0.207   1.724  -0.851   1.030   0.230  -0.171   1.128   0.271   0.134  -0.592  -0.028   0.291  -0.317   0.621  -0.027   0.472   0.588  -0.263   0.690  -0.427   1.507  -0.256   0.783  -0.003  -0.570   0.111   0.980   0.749   0.710  -0.058   0.905  -0.180   0.551   0.295   0.414   0.210  -0.755   0.581  -0.896   1.900  -0.866   1.059  -0.635   0.507   0.383   0.643   0.515  -0.471  -0.361  -0.557  -0.208  -0.397
217046 -0.395  0.524  0.492 -0.231 -0.088 -0.919 -0.283  0.608  0.168   0.099   0.599  -1.423  -0.968  -0.839  -0.900  -1.023  -0.128  -1.033  -0.780  -0.665  -0.274  -0.730  -0.887  -0.186   0.093  -0.484   0.001  -0.098   0.175  -0.695   0.622  -1.099  -0.030  -0.494   0.534  -0.805  -0.214  -0.097   0.549   0.543   0.242  -0.930   0.146   0.078  -0.192  -0.165   0.115  -0.214   0.413   0.891  -0.359  -0.277  -0.620  -0.871   0.803  -0.219   0.145  -0.104  -0.599  -0.023  -0.389  -0.109  -0.216   0.698   0.237   0.140   0.332  -0.219   0.961   0.727   0.651  -0.385  -0.118  -0.955   0.170   0.626  -0.740   0.106   0.548   0.639  -1.239  -0.432  -0.739  -0.079  -0.626   0.081   0.465  -0.190   0.042   0.559

In [ ]:
# Splitting the datasets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.025, random_state=seed)

# Printing the shapes of the new datasets
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((502461, 90), (502461,), (12884, 90), (12884,))

In [ ]:
# Writing a function to reset the indexes of the new datasets
def reset_df_index(train, test):
  train.reset_index(drop=True, inplace=True)
  test.reset_index(drop=True, inplace=True)

# Resetting the indexes
reset_df_index(X_train, y_train)
reset_df_index(X_test, y_test)

In [ ]:
X_train.to_feather(BASE_PATH + 'X_train')
y_train.to_pickle(BASE_PATH + 'y_train')
X_test.to_feather(BASE_PATH + 'X_test')
y_test.to_pickle(BASE_PATH + 'y_test')

In [ ]:
# Reading the feathered and pickled versions of the datasets
X_train = pd.read_feather(BASE_PATH + 'X_train')
y_train = pd.read_pickle(BASE_PATH + 'y_train')
X_test = pd.read_feather(BASE_PATH + 'X_test')
y_test = pd.read_pickle(BASE_PATH + 'y_test')

In [ ]:
# Importing the PyTorch library
import torch

# Importing the nn module
import torch.nn as nn

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Ensuring that the tensors and any other
# PyTorch elements that we create for this project
# can use the GPU feature if it is available
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")

# Converting the datasets into tensors
X_train = torch.tensor(X_train.values).float().to(device)
y_train = torch.tensor(y_train.values).float().to(device)
X_test = torch.tensor(X_test.values).float().to(device)
y_test = torch.tensor(y_test.values).float().to(device)

In [ ]:
# Specifying the total number of independent variables
# in our data (i.e., the number of X_train
# columns) as the size of the input to the first layer
initial_input_size = X_train.shape[1]

# Specifying the number of features that the
# first layer should output
output_size_1 = 20

# Specifying the number of features that the
# second layer should output
output_size_2 = 10

# Specifying the number of features that the
# third layer should output
output_size_3 = 5

# Setting the size of the final output as 1 because
# we want only one release year predicted per song
final_output_size = 1

In [ ]:
model = nn.Sequential(nn.Linear(initial_input_size, output_size_1),
nn.ReLU(),
nn.Linear(output_size_1, output_size_2),
nn.ReLU(),
nn.Linear(output_size_2, output_size_3),
nn.ReLU(),
nn.Linear(output_size_3, final_output_size))

In [ ]:
model.to(device)

Sequential(
  (0): Linear(in_features=90, out_features=20, bias=True)
  (1): ReLU()
  (2): Linear(in_features=20, out_features=10, bias=True)
  (3): ReLU()
  (4): Linear(in_features=10, out_features=5, bias=True)
  (5): ReLU()
  (6): Linear(in_features=5, out_features=1, bias=True)
)

In [ ]:
# Initializing MSELoss as the loss function
l_func = torch.nn.MSELoss()

# Initializing Adam
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [ ]:
for i in range(3500):
  y_pred = model(X_train).squeeze()
  loss = l_func(y_pred, y_train)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  if i%250 == 0:
    print(i, loss.item())

0 3993688.75
250 141457.953125
500 392.24615478515625
750 141.52210998535156
1000 112.24727630615234
1250 113.63682556152344
1500 101.07369995117188
1750 269.5038146972656
2000 93.56182861328125
2250 101.76188659667969
2500 91.22663116455078
2750 90.86222076416016
3000 90.9881591796875
3250 90.12720489501953

In [ ]:
pred = model(X_test[69])
print("Actual value:", y_test[69].item(), "Predicted value:", round(pred.item()))

Actual value: 2006.0 Predicted value: 2001

In [ ]:
pred = model(X_test[2000])
print("Actual value:", y_test[2000].item(), "Predicted value:", round(pred.item()))

Actual value: 2009.0 Predicted value: 2003

In [ ]:
pred = model(X_test[35])
print("Actual value:", y_test[35].item(), "Predicted value:", round(pred.item()))

Actual value: 1996.0 Predicted value: 1995